<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Order Number CA-1326956310.07.2024 - 6._127802</name>
   <tag></tag>
   <elementGuidId>30bde971-7fc6-4961-a92e-2f4b1a1cdc94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div/div[3]/a/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_info__13pug.styles_extInfo__ATd2X</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Order Recipient Order Sponsor: Istest Testi product image Order Number: CA-13269563 10.07.2024 - 6.55 AM Address Title: qaautomationalbb test $19.79 Total Points: 3.15 Order Cancelled&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a832a59-761e-45c0-955a-f748f0b87719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_info__13pug styles_extInfo__ATd2X</value>
      <webElementGuid>ffa7e1af-1aec-4716-a881-99438b3cee41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Number: CA-1326956310.07.2024 - 6.55 AMAddress Title: qaautomationalbb test$19.79Total Points: 3.15</value>
      <webElementGuid>27e23866-0254-4510-9c3c-ea9f4f6695ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container styles_container__K6XM3&quot;]/div[@class=&quot;styles_content___n5NY&quot;]/div[2]/div[@class=&quot;styles_content__LiFO2&quot;]/div[@class=&quot;styles_list__Yja4L&quot;]/a[1]/div[@class=&quot;styles_container__DE9Lb styles_justWrap__U_rhR styles_containerBorder__Ugvkr&quot;]/div[@class=&quot;styles_info__13pug styles_extInfo__ATd2X&quot;]</value>
      <webElementGuid>21f1ef4e-b1cf-455c-b178-1570d883ca5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div/div[3]/a/div/div[2]</value>
      <webElementGuid>39f4b60d-08ad-452c-948a-a6978e788c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Istest Testi'])[2]/following::div[1]</value>
      <webElementGuid>16e246b6-bf1d-4530-b501-c68dd5d44e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelled'])[1]/following::div[4]</value>
      <webElementGuid>65cc3af0-b8cd-4e9f-905d-b231ba1ca0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]</value>
      <webElementGuid>2a3c1257-38ec-4416-b08f-985a81398c28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
