<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EN_styles_image__qb0tG</name>
   <tag></tag>
   <elementGuidId>11cd140a-700b-491a-9031-e99f77ddce1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.styles_image__qb0tG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User Profile Picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1454303b-2757-4f0c-a51d-75bd654c325c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://farmasi-customer-v2.s3.eu-west-1.amazonaws.com/Profile/b739257e-616b-4132-aa25-dea995aef58c.JPG</value>
      <webElementGuid>1cd33fd9-1ac1-4290-925e-b11c0b9c4989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Profile Picture</value>
      <webElementGuid>67d7f360-115d-48db-b840-a91e891f5082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c0217c47-4c16-4957-abb5-316c8f6f8ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_image__qb0tG</value>
      <webElementGuid>8024fa9d-ab64-4f88-9206-e8ea4f943c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container styles_headerUpper__diGEV&quot;]/div[@class=&quot;styles_headerUpperRight__ZW4WC&quot;]/div[@class=&quot;styles_container__A_H4H&quot;]/div[1]/div[1]/div[@class=&quot;styles_container__BfiT7&quot;]/img[@class=&quot;styles_image__qb0tG&quot;]</value>
      <webElementGuid>373a244d-0701-4fdc-a021-a669a425ec99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>90572924-2315-4c31-91b5-657b8ad7d2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Profile Picture']</value>
      <webElementGuid>e2fe40ff-a306-4660-a1f9-56bab0fe1a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>3e39c290-68ca-4ee1-ba11-88ccd02dfae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
