<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1119082</name>
   <tag></tag>
   <elementGuidId>ad1af1f3-17c8-4103-831a-456350cd23b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div[2]/div[5]/div/div/div/div[2]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.styles_listItemCode__yV_O6.styles_defaults__ttgfN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1119082&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9ad29d67-4cd1-4094-a9e4-fc38b9be13b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_listItemCode__yV_O6 styles_defaults__ttgfN undefined</value>
      <webElementGuid>2e0208a2-ed59-42fc-b307-a956d57832f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1119082</value>
      <webElementGuid>b787de5b-68cc-4dec-8a75-a111abf3ce33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;checkoutSuccess_productList__eJqZs&quot;]/div[@class=&quot;styles_list___1v8h&quot;]/div[@class=&quot;styles_listItem__zn0QY&quot;]/div[@class=&quot;styles_listItemInfo__nUriW&quot;]/div[2]/p[@class=&quot;styles_listItemCode__yV_O6 styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>841488a0-ea06-43f3-a04f-48ecacfbaf7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[5]/div/div/div/div[2]/p[2]</value>
      <webElementGuid>92928c7b-9470-471b-9754-93b006e8a7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::p[2]</value>
      <webElementGuid>ffd1fc9e-15b1-48cb-b5b7-650acddbb41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$19.25'])[3]/following::p[2]</value>
      <webElementGuid>9faf3b44-676a-445d-a4ce-a5c61c903536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$8.00'])[1]/preceding::p[1]</value>
      <webElementGuid>d82372bc-097b-4875-9ae6-150102c40bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 8.00'])[1]/preceding::p[1]</value>
      <webElementGuid>5e9fd5d9-6911-4fdc-bd55-69bdfbaa3599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1119082']/parent::*</value>
      <webElementGuid>a74079d3-a85b-49f7-bb55-78e898b7c8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]</value>
      <webElementGuid>b44d3d71-0fd3-4862-bd87-d8b41afed3f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
