<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_CA-13283148</name>
   <tag></tag>
   <elementGuidId>914bc87e-9a05-41c4-b52b-6fd7fdc715fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/main/div[2]/div[3]/div/div[2]/div[1]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.styles_address__DK6vF.styles_defaults__ttgfN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CA-13283148&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4bb37415-4193-4012-948b-aeb241c22e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_address__DK6vF styles_defaults__ttgfN undefined</value>
      <webElementGuid>41e36a64-d62d-4c5e-a202-aa23107e9737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA-13283148</value>
      <webElementGuid>33368beb-bf72-435a-bfaf-8e596e48c49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;checkoutSuccess_orderAddresses__5tyZ4&quot;]/div[@class=&quot;styles_container__3wsif&quot;]/div[@class=&quot;styles_info__EQVxw&quot;]/div[1]/div[1]/p[@class=&quot;styles_address__DK6vF styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>56680e00-80c4-4782-97ee-667b01030da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div[2]/div[3]/div/div[2]/div/div/p</value>
      <webElementGuid>2f982277-c64d-45d9-a3b9-ffbdad2918f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order No:'])[1]/following::p[1]</value>
      <webElementGuid>73274b96-689a-4c95-aa03-5f6244594066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fdfsfggdfsdeasdfbfd, Gogama, Canada. t3r 4f5.'])[2]/following::p[1]</value>
      <webElementGuid>00e08f00-c1e1-4e91-a3b3-aca6ced0ccc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price:'])[1]/preceding::p[1]</value>
      <webElementGuid>97199a1f-ffa5-4186-9835-c14050187b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[1]/preceding::p[2]</value>
      <webElementGuid>98332d75-379c-4d9b-a057-688325bd2b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA-13283148']/parent::*</value>
      <webElementGuid>250071af-1a96-4c2d-9faa-316eaa3d7fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p</value>
      <webElementGuid>9b917683-cd06-4973-bc0e-df0d397a0417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
