<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1119082</name>
   <tag></tag>
   <elementGuidId>fcf61e5e-f515-4b2d-a21a-8df126d51c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.styles_semibold__y5tww.productDetail_productInfoCode__ZKAR_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1119082&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3789f5f4-02ba-46d2-ba87-5c76bf78488e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_semibold__y5tww productDetail_productInfoCode__ZKAR_</value>
      <webElementGuid>9cce0cf4-7b2d-4a2b-9e1e-a177cdfc611f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1119082</value>
      <webElementGuid>b2ec98ca-e5cc-49dd-b75b-873d2d361910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container productDetail_card__U7wi2&quot;]/div[@class=&quot;productDetail_productInfo__X6dWh&quot;]/span[@class=&quot;productDetail_productInfoCode__ZKAR_ styles_defaults__ttgfN undefined&quot;]/span[@class=&quot;styles_semibold__y5tww productDetail_productInfoCode__ZKAR_&quot;]</value>
      <webElementGuid>028ae379-d104-49a9-b0ba-da5d3dae0326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/span/span</value>
      <webElementGuid>f78d47b3-7fa3-4dae-ae14-6f8cc0050763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shield Man Shampoo'])[1]/following::span[2]</value>
      <webElementGuid>8f0fe8a0-f7e2-4eff-9e2c-b9880b87e253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16.00'])[1]/preceding::span[5]</value>
      <webElementGuid>64854be4-cea2-433d-81c5-e7fc4440eb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1119082']/parent::*</value>
      <webElementGuid>f1f3681f-5808-4f27-be91-9fa94f1fee50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>c2921a0f-7dfe-4739-aaa9-a15b84b056d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
