<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CA-13283148</name>
   <tag></tag>
   <elementGuidId>d36565ab-fd57-40ec-a503-a978a08f0df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/main/div[1]/div[2]/div[2]/div/div[3]/a[1]/div/div[2]/div[2]/div[1]/div[1]/h6/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.styles_bold__zPuLl.styles_infoDataOrderNo__CjqaG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Order Recipient Order Sponsor: Farmasi Root product image Order Number: CA-13283148 10.08.2024 - 8.56 AM Address Title: grgrg grgrhgrf $19.25 Total Points: 5.93 Order Cancelled&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a0bae40-534e-4439-8c46-3cb9b799b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_bold__zPuLl styles_infoDataOrderNo__CjqaG</value>
      <webElementGuid>a67b9625-a1b4-4a9c-a3c8-98b4c267c394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA-13283148</value>
      <webElementGuid>3d674696-6716-4a02-8c16-4309c9003031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container styles_container__K6XM3&quot;]/div[@class=&quot;styles_content___n5NY&quot;]/div[2]/div[@class=&quot;styles_content__LiFO2&quot;]/div[@class=&quot;styles_list__Yja4L&quot;]/a[1]/div[@class=&quot;styles_container__DE9Lb styles_justWrap__U_rhR styles_containerBorder__Ugvkr&quot;]/div[@class=&quot;styles_info__13pug styles_extInfo__ATd2X&quot;]/div[@class=&quot;styles_infoData__kKbfB&quot;]/div[1]/div[@class=&quot;styles_infoDataOrderWrapper__Tprxb&quot;]/h6[@class=&quot;styles_infoDataOrderNo__CjqaG styles_defaults__ttgfN undefined&quot;]/span[@class=&quot;styles_bold__zPuLl styles_infoDataOrderNo__CjqaG&quot;]</value>
      <webElementGuid>e4547695-fad1-4706-a05c-6b19a5d88610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div/div[3]/a/div/div[2]/div[2]/div/div/h6/span</value>
      <webElementGuid>a3d669b4-72c7-4342-85b2-8157734def3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Root'])[1]/following::span[1]</value>
      <webElementGuid>55128f71-38b2-416d-97d4-6a95bc2b6370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='grgrg grgrhgrf'])[1]/preceding::span[2]</value>
      <webElementGuid>4167dbf4-4bb7-4343-8701-d6fcbc46a30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA-13283148']/parent::*</value>
      <webElementGuid>59ea8269-7446-4bd2-a0e2-1dc99b6c7e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6/span</value>
      <webElementGuid>4cb99ec1-19f3-4c51-aa45-107aba5607f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
