<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel Order</name>
   <tag></tag>
   <elementGuidId>3e5b7a03-e3eb-4e0c-8131-c64340efbc38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles_btn__x0Jp4.styles_btnsmall__huzcL.styles_outline__2nNnh.false.false.styles_roundedmedium__ojrBR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel Order&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33b4d929-fe39-40e9-b1ef-a620eb0a5254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e1549ce-46f2-43ca-b3a7-059ec415ad44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_btn__x0Jp4 styles_btnsmall__huzcL styles_outline__2nNnh false false styles_roundedmedium__ojrBR </value>
      <webElementGuid>cb1a0e32-99e7-48d3-96b0-89d3ec0bca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel Order</value>
      <webElementGuid>839a33f6-477f-49cd-965b-9ce62ba17a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container&quot;]/div[@class=&quot;orderDetail_status__FRFdZ&quot;]/div[@class=&quot;styles_container__KQXjr&quot;]/div[@class=&quot;styles_steps__PIgDx&quot;]/div[@class=&quot;styles_stepsItem__Z164m&quot;]/div[@class=&quot;styles_mt__OPbWE&quot;]/div[1]/button[@class=&quot;styles_btn__x0Jp4 styles_btnsmall__huzcL styles_outline__2nNnh false false styles_roundedmedium__ojrBR&quot;]</value>
      <webElementGuid>1be97d75-145c-420d-8664-b8bd20e2f9ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>961daa0e-5873-4bb0-af04-ddf1fa909c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[3]/div[2]/div/div/div[3]/div/button</value>
      <webElementGuid>a8f28eec-6185-4fbe-9934-d0b67e7fcd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order is awaiting confirmation'])[1]/following::button[1]</value>
      <webElementGuid>ab3fdf27-a6a7-48b0-a975-c5c861427abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Root'])[2]/following::button[1]</value>
      <webElementGuid>90c47bcf-8e0c-47b1-b687-4888bd13db9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Preparing'])[1]/preceding::button[1]</value>
      <webElementGuid>c0bcb10e-5f12-471d-9ff7-ccbe5df6fdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>76c0df2a-df8d-49dc-93a1-f3d2ff9fd213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cancel Order' or . = 'Cancel Order')]</value>
      <webElementGuid>17548442-e511-42c2-bee8-087bc9dfcedd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
