<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_t</name>
   <tag></tag>
   <elementGuidId>c54d18cb-fe00-4799-bdf5-f1cb7061da31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;cancelReasonArea&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='cancelReasonArea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cancel Reason&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ed62dd3-ee5c-44c2-b5c8-2ce8ccb85162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelReasonArea</value>
      <webElementGuid>490c78e6-ad1f-4729-89ba-c2cb0079e241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cancel Reason</value>
      <webElementGuid>09397f45-9ebb-4ea1-b558-3c6ff484c19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d10641dc-8b75-4404-b1c5-c88915af70b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__tFS_Y styles_inputFocused__f2_zm form-control</value>
      <webElementGuid>74badce3-b60c-4b6b-b693-c5f85e9d4643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>f3d04724-3e86-4477-8956-293ab72980fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_window__xaCFD styles_roundedxLarge___jtqx undefined&quot;]/div[@class=&quot;styles_content__Yf1T7 styles_modalPadding__0mbnS styles_maxContentHeight__wZWPT undefined&quot;]/div[1]/div[2]/div[2]/div[@class=&quot;styles_inputGroup__DU0_L styles_inputGroupFocused__zrfgr  false&quot;]/div[@class=&quot;styles_inputContainer__cc_Aw&quot;]/div[@class=&quot;styles_floatingLabel__BTt5O form-floating&quot;]/textarea[@class=&quot;styles_input__tFS_Y styles_inputFocused__f2_zm form-control&quot;]</value>
      <webElementGuid>f79fad91-ebaa-4dce-856a-276180ab4a64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='cancelReasonArea']</value>
      <webElementGuid>55364aa0-73ab-4460-a106-80e4dd2f9004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Wallet'])[2]/following::textarea[1]</value>
      <webElementGuid>ce72ee0f-f3a5-48f1-9143-8d4ed7ea0832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Payment Type'])[1]/following::textarea[1]</value>
      <webElementGuid>6f3ec099-b881-43d6-b350-550214644b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Reason'])[1]/preceding::textarea[1]</value>
      <webElementGuid>4d763b68-da35-4dea-a9cb-4c41b9bbc236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/preceding::textarea[1]</value>
      <webElementGuid>fd2c6792-538b-4eda-b650-995d40668b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t']/parent::*</value>
      <webElementGuid>0fe7834d-fed9-4aab-9e39-b8ced65d2176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c70343d2-eb2b-494a-a6ec-65ae2b6fa349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'cancelReasonArea' and @placeholder = 'Cancel Reason' and (text() = 't' or . = 't')]</value>
      <webElementGuid>7541bcae-7a48-47c1-b018-9286a5761597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
