<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_zferfgrg_styles_cardHeaderRadioActive___dc40d8</name>
   <tag></tag>
   <elementGuidId>6812fc5d-e251-4576-81a1-6c2fd8dff673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_cardHeaderRadioActive__8Lbcs.false</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog >> div >> internal:has-text=/^zferfgrg$/ >> div >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87141a4d-4373-4ba9-8317-106be2d39c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_cardHeaderRadioActive__8Lbcs false</value>
      <webElementGuid>6442fa28-a5e4-449c-a4d5-cdc2a9e631ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_wrapper__A5bP8 offcanvas offcanvas-end show&quot;]/div[3]/div[@class=&quot;styles_content__mXE7e undefined false false styles_heightWithButtonAndSearch___adJO&quot;]/div[@class=&quot;styles_container__5GTc7&quot;]/div[@class=&quot;styles_addressesContainer___b7KK&quot;]/div[2]/div[@class=&quot;styles_card__E6rE8 false false&quot;]/div[1]/div[@class=&quot;styles_cardHeader__BC4Os&quot;]/div[@class=&quot;styles_cardHeaderRadio__LRBVj&quot;]/div[@class=&quot;styles_cardHeaderRadioActive__8Lbcs false&quot;]</value>
      <webElementGuid>e470f8a8-72c5-44a6-8594-81486d03547c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>e0e14925-becd-4f1d-bae3-7bbe652a96fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
