<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EN_styles_image__qb0tG</name>
   <tag></tag>
   <elementGuidId>01646b12-c15f-4642-9e07-1fa643c35873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.styles_image__qb0tG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User Profile Picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4984fdd-1fa0-4bf5-9c63-13538dffb5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://farmasi-customer-v2.s3.eu-west-1.amazonaws.com/Profile/b739257e-616b-4132-aa25-dea995aef58c.JPG</value>
      <webElementGuid>8a5e6386-0db8-4204-898d-515472a87515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Profile Picture</value>
      <webElementGuid>cc2fa8ad-3ad6-41ec-97dc-7a9ba03db2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d25de0cd-90e4-49d8-9022-1018f21f4168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_image__qb0tG</value>
      <webElementGuid>db2c3314-62b3-4c68-95c4-50e382afcac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container styles_headerUpper__diGEV&quot;]/div[@class=&quot;styles_headerUpperRight__ZW4WC&quot;]/div[@class=&quot;styles_container__A_H4H&quot;]/div[1]/div[1]/div[@class=&quot;styles_container__BfiT7&quot;]/img[@class=&quot;styles_image__qb0tG&quot;]</value>
      <webElementGuid>88b5bf4a-70a0-4899-bbad-402e51c11286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>7fc4d4a5-7fa7-4405-a5b9-47a6d16a6435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Profile Picture']</value>
      <webElementGuid>73e24b75-f3ec-4c62-b5c5-a14f86495896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>d90d57d3-3242-4f4a-ab22-30317a853ae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
