<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Testdenemeotomasyon</name>
   <tag></tag>
   <elementGuidId>4c8b535d-26ad-4455-91a2-fc679b51124c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div/div/a/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.styles_heading__HQEPI.styles_defaults__ttgfN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Testdenemeotomasyon Public Testdenemeotomasyon - 0 Testdenemeotomasyon - 1 Testdenemeotomasyon - 2 Testdenemeotomasyon - 3 Testdenemeotomasyon - 4 Testdenemeotomasyon - 5 Testdenemeotomasyon - 6&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>4ecb1f30-403d-467b-8e6f-0a266044c58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_heading__HQEPI styles_defaults__ttgfN undefined</value>
      <webElementGuid>0cd7dd03-5919-49c8-8691-1330b7053c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testdenemeotomasyon</value>
      <webElementGuid>dc741af4-8984-4b45-8633-858b6b5420ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container styles_container__K6XM3&quot;]/div[@class=&quot;styles_content___n5NY&quot;]/div[@class=&quot;wishlist_container__VYBPp&quot;]/div[1]/div[@class=&quot;styles_container__GW07_&quot;]/a[@class=&quot;w-100&quot;]/div[@class=&quot;styles_item__LW3p7&quot;]/div[@class=&quot;styles_header__2jPWJ&quot;]/div[1]/h3[@class=&quot;styles_heading__HQEPI styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>e6dac80c-1acc-4542-9fe5-91811d991b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div/div/a/div/div/div/h3</value>
      <webElementGuid>d5aba19a-2d6c-48da-9784-5b9fc9ddf527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New List'])[1]/following::h3[1]</value>
      <webElementGuid>16324a3c-38a5-4d08-9a66-6cd557b25658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotlist'])[3]/following::h3[1]</value>
      <webElementGuid>c1f5ff1c-642a-438c-9f5f-07212388299a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/preceding::h3[1]</value>
      <webElementGuid>fddeafc7-2cc8-4c41-a8a3-b42e5b6d8785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove List'])[1]/preceding::h3[1]</value>
      <webElementGuid>3844b69d-f6b6-4e69-8109-91479ae2f3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testdenemeotomasyon']/parent::*</value>
      <webElementGuid>90ffe4b7-54a0-4ccf-a3d3-8e282e335211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>bc356ded-782c-49a0-843a-12ec3bc6ee3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Testdenemeotomasyon' or . = 'Testdenemeotomasyon')]</value>
      <webElementGuid>7a555b0f-94b0-4d9b-aa8e-5b6bdc968bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
