<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otomasyon_id</name>
   <tag></tag>
   <elementGuidId>7dad42e0-a9bb-479e-868e-67e7776679ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/form/div[1]/ul/li[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;otomasyon&quot;i >> [data-testid=&quot;selectListItem&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c1d87e5-7785-4439-95af-509289ebec7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__bxkI7</value>
      <webElementGuid>60b42735-70c9-48c3-841f-8b2cbd70e3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c0ff30c1-d045-4ff3-ab93-cfa183646dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>09b52662-e18b-452f-bebc-d31b0bc83eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0eb8b252-ad97-4eaf-b970-5f79b8369cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>selectListItem</value>
      <webElementGuid>3b51a7b9-406f-49eb-96c6-e3fde6f9657a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3124e1ac-cef6-48ea-b0e0-c5351d56a63a</value>
      <webElementGuid>c7371a66-65c2-4ca1-844d-9a2a17c81b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_window__xaCFD styles_roundedmedium__nXKE3 undefined&quot;]/div[@class=&quot;styles_content__Yf1T7 false false styles_modalContent__egyQe&quot;]/form[@class=&quot;styles_container__io7kX&quot;]/div[1]/ul[@class=&quot;styles_list__oBW0Z&quot;]/li[@class=&quot;styles_listItem__vG00U&quot;]/div[1]/div[@class=&quot;styles_containerCheckBox__1uCkp&quot;]/input[@class=&quot;styles_input__bxkI7&quot;]</value>
      <webElementGuid>45488d95-0303-4a9a-95f6-df0d8363e31a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@data-testid = 'selectListItem']</value>
      <webElementGuid>60c6c207-e7ae-4f22-9b58-584c69c7b270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='id']</value>
      <webElementGuid>628c2760-0410-4647-8bb3-44714be2c866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>f66af694-69ac-4ad2-a20b-21855f99975f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
