<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Return Payment Type_styles_radio__4_6lP</name>
   <tag></tag>
   <elementGuidId>9f57121b-7f3a-4257-87da-3fdf69cf8e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[4]/div[2]/div/div[2]/div[1]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_radio__4_6lP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Farmasi Wallet&quot;i >> div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86c9e461-5e25-46c8-b5d5-28adee84973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_radio__4_6lP</value>
      <webElementGuid>a8c5cf06-ee49-4881-9357-5a90fc69d5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_window__xaCFD styles_roundedxLarge___jtqx undefined&quot;]/div[@class=&quot;styles_content__Yf1T7 styles_modalPadding__0mbnS styles_maxContentHeight__wZWPT undefined&quot;]/div[1]/div[2]/div[@class=&quot;styles_radioContainer__vD0Sm&quot;]/label[@class=&quot;styles_radioContainer__JpZ8s styles_radioButton__PMrcY&quot;]/div[@class=&quot;styles_radio__4_6lP&quot;]</value>
      <webElementGuid>645cb03a-1c7d-4edd-afe0-b1b805035a63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>2d77addb-185b-4d8c-92ad-e6577cc69cac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
