<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Men</name>
   <tag></tag>
   <elementGuidId>8339866f-0bdd-44cb-a059-8d947aaa7ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainCategoryItem8 > a.styles_mainCategoryLink___k5XX.false > div.styles_mainCategoryTitle__iIvl7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainCategoryItem8']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Men&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ae5dd48-3f1a-4de9-ad54-343b5ad73b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_mainCategoryTitle__iIvl7</value>
      <webElementGuid>7fd92c04-1d48-4b43-98a7-e55101d7ba70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men</value>
      <webElementGuid>b330dfec-d83f-487d-93e8-52516da3f9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainCategoryItem8&quot;)/a[@class=&quot;styles_mainCategoryLink___k5XX false&quot;]/div[@class=&quot;styles_mainCategoryTitle__iIvl7&quot;]</value>
      <webElementGuid>07703509-878a-4b90-bbd1-c3f7fbc6ebd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainCategoryItem8']/a/div</value>
      <webElementGuid>f849c686-058b-4866-85e6-eea569f659b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[2]/following::div[2]</value>
      <webElementGuid>8ee42a5d-032f-4d62-9a66-28ee161b14ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multipurpose Cleaner'])[1]/following::div[4]</value>
      <webElementGuid>7038c5c7-0eed-4c7e-9367-a2b49b9b87be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand Tools'])[1]/preceding::div[3]</value>
      <webElementGuid>b5650b9e-781a-403c-8a17-5965b8ec37af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support Items'])[1]/preceding::div[6]</value>
      <webElementGuid>01f9acaf-1eb7-4e95-96ed-20504fb676cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Men']/parent::*</value>
      <webElementGuid>f823394d-02d1-41b6-a381-e96d6b9d9fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a/div</value>
      <webElementGuid>9afb94bb-efe9-40ef-ad26-1e48f6d571a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
