<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EN_styles_image__qb0tG</name>
   <tag></tag>
   <elementGuidId>cb5eb31d-420c-466e-8217-5b0b198994fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.styles_image__qb0tG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User Profile Picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>064efffd-cb3c-47da-8355-1416f9f1aa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://farmasi-customer-v2.s3.eu-west-1.amazonaws.com/Profile/b739257e-616b-4132-aa25-dea995aef58c.JPG</value>
      <webElementGuid>e9b6174a-2ad1-4952-8732-0fa18c042c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Profile Picture</value>
      <webElementGuid>20762d19-ad43-41f2-b82d-380da67535c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>ae954cf4-4e23-465c-875a-ca0e31b5b532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_image__qb0tG</value>
      <webElementGuid>251c1a2a-049e-4a29-a87e-4b42b7251e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container styles_headerUpper__diGEV&quot;]/div[@class=&quot;styles_headerUpperRight__ZW4WC&quot;]/div[@class=&quot;styles_container__A_H4H&quot;]/div[1]/div[1]/div[@class=&quot;styles_container__BfiT7&quot;]/img[@class=&quot;styles_image__qb0tG&quot;]</value>
      <webElementGuid>8f595cad-dff7-4378-a88a-08b19caac8b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>fb53624b-a648-4e33-94de-acae80b2756e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Profile Picture']</value>
      <webElementGuid>1f489261-62dd-4a48-8a28-149f67ff87dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>c936a137-4059-4104-a45d-88d23aa96cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
