<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check</name>
   <tag></tag>
   <elementGuidId>4ab13b26-efb2-42c3-b22c-9f38f307eb0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles_inputBtn__o65gF.false</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-testid = 'inputButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;inputButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5b91b52-b5e5-4ccb-990a-4f50cabd7abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_inputBtn__o65gF false  </value>
      <webElementGuid>f18a5d28-4acb-4752-a24f-a7ca48af0528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>210cc3ee-89fe-407d-bcc6-6b17625b615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>inputButton</value>
      <webElementGuid>617dd183-8d9d-4869-b495-062e4dd2419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check</value>
      <webElementGuid>13363aa1-ca15-4888-b3a5-ff76378bb723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;styles_container__kr9mt&quot;]/div[@class=&quot;styles_formContainer__e6qvX&quot;]/form[@class=&quot;styles_form__0RINI undefined&quot;]/div[@class=&quot;styles_rowFull__yAhc0 styles_rowGroupedDestroyed__WMdQJ&quot;]/div[@class=&quot;styles_container__cv5IV undefined&quot;]/div[@class=&quot;styles_inputContainer__MzORs&quot;]/div[@class=&quot;styles_inputGroup__ro902 false  false styles_inputGroupReverse__VOiCp&quot;]/div[@class=&quot;styles_iconGroup__d8wY1 undefined&quot;]/button[@class=&quot;styles_inputBtn__o65gF false&quot;]</value>
      <webElementGuid>653c0380-4570-46f5-baa3-bed1821a6f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@data-testid = 'inputButton']</value>
      <webElementGuid>81762ba5-ce96-4f5e-b6bc-c8b54c1781a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>ecc629c1-9cc7-471a-903a-1ff09c3b679a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/form/div[16]/div/div[2]/div/div[2]/button</value>
      <webElementGuid>d7415187-5db0-476f-af8f-793f70be1b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sponsor Code'])[1]/following::button[1]</value>
      <webElementGuid>33e14a94-bd66-454b-b505-24e3faf6dda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi and Privacy Policy.'])[1]/preceding::button[1]</value>
      <webElementGuid>7952cba7-5d03-4a68-97d1-a23a61648eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c42b261a-88fb-4a4d-bb36-54456dde83e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
