<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Farmasi and Privacy Policy_agreement2</name>
   <tag></tag>
   <elementGuidId>a78dc97e-0244-486c-97cf-a2d1e734558a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agreement2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'agreement2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#agreement2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>096173d9-d9fc-4cc3-b950-512e783a9cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__bxkI7</value>
      <webElementGuid>f5449dd4-648f-4707-9799-d7841bc93878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b73ea6df-af9f-4af5-8cf9-7b397dfe0c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreement2</value>
      <webElementGuid>e5659f7f-daac-472f-beec-7f12c8a06b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agreement2</value>
      <webElementGuid>87b997e3-f2d3-4e1a-b7da-28e0d3d3512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47cc4823-2433-4c23-8515-8d5004d56225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreement2&quot;)</value>
      <webElementGuid>630e9591-8543-4756-aa2c-d39cebef744b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'agreement2']</value>
      <webElementGuid>4d8491e4-698b-4794-a2bb-47da38d82e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agreement2']</value>
      <webElementGuid>ecd7744c-2935-4eaa-8cae-e65010471738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/form/div[18]/div/div/div/div/input</value>
      <webElementGuid>3486e488-1b4f-46cb-8973-b1491d474b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/div/input</value>
      <webElementGuid>cd036080-1141-4301-839e-45e5bd7fe5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
