<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select City_postCode</name>
   <tag></tag>
   <elementGuidId>28bbd636-326f-44e7-b809-eef687a06580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Postal Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>739aeece-c8a8-4b26-be84-35cd968e3bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postCode</value>
      <webElementGuid>194f197c-effa-40ef-a945-e5f67f1fe374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Postal Code</value>
      <webElementGuid>e65240f7-fd2e-4e67-8bb1-c05e2d1e8c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>1b1c3847-eab8-483c-a0c8-5808c457009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6327089-6097-4531-b021-480a2c5b9bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postCode</value>
      <webElementGuid>67e6acd2-f815-4de4-bc02-19b773eb7abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__ZqX_f styles_inputFocused__20paC   form-control</value>
      <webElementGuid>b5d51b2b-bc84-4531-8e3b-ee1bf8d5af29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postCode&quot;)</value>
      <webElementGuid>105aa2f2-d3f6-4458-962a-ff4e607d2acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postCode']</value>
      <webElementGuid>29f3f575-31e7-4497-abd2-59aab773dde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/input</value>
      <webElementGuid>0f603115-8ff5-44e4-9529-61e96e7f099e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'postCode' and @placeholder = 'Postal Code' and @type = 'text' and @id = 'postCode']</value>
      <webElementGuid>0fc97ce9-a350-4d2e-9690-2e36a97467cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
