<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Abee_city</name>
   <tag></tag>
   <elementGuidId>bfce249f-6adf-4753-866c-9abdd746485d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ba00508c-6324-ec11-b6e7-000d3a700d6c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ba00508c-6324-ec11-b6e7-000d3a700d6c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ba00508c-6324-ec11-b6e7-000d3a700d6c</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4b56754-175d-4c45-ab2f-83ae08adb541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>94072c75-9e3a-4ed6-b2a4-d46998973dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_radio__1PmVS</value>
      <webElementGuid>2fee40d0-b773-407d-874f-9c53ef7a9c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>22b75522-61a1-4bdc-b715-848bbb4b6c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ba00508c-6324-ec11-b6e7-000d3a700d6c</value>
      <webElementGuid>6323d24f-cf03-4c3f-8636-bc543cfcf890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ba00508c-6324-ec11-b6e7-000d3a700d6c</value>
      <webElementGuid>47a31a05-cd1d-4865-b46d-acbd3e764858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ba00508c-6324-ec11-b6e7-000d3a700d6c&quot;)</value>
      <webElementGuid>0eddb7a6-0d9b-439e-84b2-3997363f786b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ba00508c-6324-ec11-b6e7-000d3a700d6c']</value>
      <webElementGuid>9e0459b9-5b18-4a74-8880-67cebf3a09f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>143c732d-a5e9-4bfb-bc54-246d088c5cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'city' and @id = 'ba00508c-6324-ec11-b6e7-000d3a700d6c']</value>
      <webElementGuid>ab96b2ea-e674-43aa-82bd-b21df0c9cd0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
