<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FARMAS  All rights reserved_styles_back_d891ac</name>
   <tag></tag>
   <elementGuidId>044350ca-ecf1-4a86-a325-1c3d6e10532f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid = 'modalBackground']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_background__GS2RW.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;modalBackground&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acdccfe3-34e8-4557-abd9-6e1a38da94cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_background__GS2RW undefined</value>
      <webElementGuid>12862af3-2a2b-4e9d-b9bd-c266d3e1ea55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>modalBackground</value>
      <webElementGuid>ac50a762-ae4d-4664-964f-1291bfa73939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_background__GS2RW undefined&quot;]</value>
      <webElementGuid>04a41f8e-e44c-42b7-8926-b92f2d2245a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'modalBackground']</value>
      <webElementGuid>ce6d4096-7771-4c4a-9b03-9c51c40b5f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>732342b8-4ef4-4fe4-9344-5e5cc16d8f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
