<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Tes</name>
   <tag></tag>
   <elementGuidId>b37d74c2-3a38-4a0f-91c8-d2908f5ef8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='cancelReasonArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;cancelReasonArea&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cancel Reason&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bdfb384d-b88e-4e78-8362-e606f48c96c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelReasonArea</value>
      <webElementGuid>63f2c3ea-73ed-4585-a727-f0c16e1dba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cancel Reason</value>
      <webElementGuid>089374f6-e0cb-4577-8a72-db8060d4092f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9d60e77e-9d3c-476b-aaa7-e95fc0a7ea50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__tFS_Y styles_inputFocused__f2_zm form-control</value>
      <webElementGuid>db925779-46ce-4b2c-bcb6-ba8d3e7ed473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tes</value>
      <webElementGuid>80f3883e-a33c-48af-9abb-2140079e6726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_window__xaCFD styles_roundedxLarge___jtqx undefined&quot;]/div[@class=&quot;styles_content__Yf1T7 styles_modalPadding__0mbnS styles_maxContentHeight__wZWPT undefined&quot;]/div[1]/div[2]/div[2]/div[@class=&quot;styles_inputGroup__DU0_L styles_inputGroupFocused__zrfgr  false&quot;]/div[@class=&quot;styles_inputContainer__cc_Aw&quot;]/div[@class=&quot;styles_floatingLabel__BTt5O form-floating&quot;]/textarea[@class=&quot;styles_input__tFS_Y styles_inputFocused__f2_zm form-control&quot;]</value>
      <webElementGuid>13ce5372-0c82-42e6-960d-ada152e0cc7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='cancelReasonArea']</value>
      <webElementGuid>61b2740e-b966-4ff3-b8d8-561d27125cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Wallet'])[2]/following::textarea[1]</value>
      <webElementGuid>886d5e1d-9c61-445e-85b8-9d1b1c56894c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Payment Type'])[1]/following::textarea[1]</value>
      <webElementGuid>00c7a36d-fca3-424a-ad36-5618b73113be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Reason'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6a899f9e-bb7c-410f-ac12-4ba67676bc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d2ab1be0-6b4d-4b79-aeae-61004ed919b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tes']/parent::*</value>
      <webElementGuid>9d37df93-845e-411c-8251-65a4fe711632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3effc3e8-3a4d-418a-98fc-32aa26533cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'cancelReasonArea' and @placeholder = 'Cancel Reason' and (text() = 'tes' or . = 'tes')]</value>
      <webElementGuid>3d3edbfc-28ad-4a96-8889-48cbc0aa44bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tes']/parent::*</value>
      <webElementGuid>e1d5532c-d27c-4047-8bf3-dda329559e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'cancelReasonArea' and @placeholder = 'Cancel Reason' and (text() = 'Tes' or . = 'Tes')]</value>
      <webElementGuid>0d73601f-d945-4be7-b808-9f1202c9c5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
