<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_T</name>
   <tag></tag>
   <elementGuidId>0144466e-1c4d-4c6c-a8d8-26e182d4210d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='cancelReasonArea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;cancelReasonArea&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cancel Reason&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7e70525f-5804-4447-9a68-2be16d1a2294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelReasonArea</value>
      <webElementGuid>fbd0e15d-9682-471e-944a-8e1862d0be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cancel Reason</value>
      <webElementGuid>749ae94d-ea1d-4a31-8696-ff93f0643995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bf67ee20-a36d-4b0e-b96a-32d0f0ece44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__tFS_Y styles_inputFocused__f2_zm form-control</value>
      <webElementGuid>66ea1c86-4528-4f32-a8d1-9afe200dc904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>965a1885-5c85-4590-b537-abdab73d97c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;styles_window__xaCFD styles_roundedxLarge___jtqx undefined&quot;]/div[@class=&quot;styles_content__Yf1T7 styles_modalPadding__0mbnS styles_maxContentHeight__wZWPT undefined&quot;]/div[1]/div[2]/div[2]/div[@class=&quot;styles_inputGroup__DU0_L styles_inputGroupFocused__zrfgr  false&quot;]/div[@class=&quot;styles_inputContainer__cc_Aw&quot;]/div[@class=&quot;styles_floatingLabel__BTt5O form-floating&quot;]/textarea[@class=&quot;styles_input__tFS_Y styles_inputFocused__f2_zm form-control&quot;]</value>
      <webElementGuid>e515abbc-49c5-4ab8-af7f-e64b715b2e47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='cancelReasonArea']</value>
      <webElementGuid>216ac762-6877-4627-b703-c34316a704a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Wallet'])[2]/following::textarea[1]</value>
      <webElementGuid>3d39c6b3-d5a2-4a5d-9d08-907d53f72bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Payment Type'])[1]/following::textarea[1]</value>
      <webElementGuid>2ee459fd-a356-4616-9661-1082bad41523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Reason'])[1]/preceding::textarea[1]</value>
      <webElementGuid>0a2360ed-fa22-4679-a329-998d05b22792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d4b1c6fc-b541-4480-8c6b-4ebac5322217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t']/parent::*</value>
      <webElementGuid>a82d88a5-3f25-4a37-a4c8-447dbaa359b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>87ab0344-e52e-4c25-8ff4-d464fc651d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'cancelReasonArea' and @placeholder = 'Cancel Reason' and (text() = 't' or . = 't')]</value>
      <webElementGuid>08988f3e-b9ac-426e-a95b-e7d4922214ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='T']/parent::*</value>
      <webElementGuid>837c2ab3-d15f-4263-9401-f5a89ee3a99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'cancelReasonArea' and @placeholder = 'Cancel Reason' and (text() = 'T' or . = 'T')]</value>
      <webElementGuid>cb88d25e-02fb-43de-b546-a4064d2d64e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
