<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Men</name>
   <tag></tag>
   <elementGuidId>fbff5032-ae68-44f9-8d95-c01fbf9fa0c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainCategoryItem8']/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainCategoryItem8 > a.styles_mainCategoryLink___k5XX.false > div.styles_mainCategoryTitle__iIvl7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Men&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef80e2b0-aa51-4921-9a38-285b231d721a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_mainCategoryTitle__iIvl7</value>
      <webElementGuid>b56367b5-2b3f-4cce-be79-ed3713346818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men</value>
      <webElementGuid>53d8dcc5-4d28-4214-9606-ae4835eb8c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainCategoryItem8&quot;)/a[@class=&quot;styles_mainCategoryLink___k5XX false&quot;]/div[@class=&quot;styles_mainCategoryTitle__iIvl7&quot;]</value>
      <webElementGuid>8153e21b-ba64-48d1-b9be-5a657bfb73dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainCategoryItem8']/a/div</value>
      <webElementGuid>fa4b9e54-9059-4e2f-abb5-34cc1128610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[2]/following::div[2]</value>
      <webElementGuid>0fa3336c-9539-49a9-b463-6de2d757a57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multipurpose Cleaner'])[1]/following::div[4]</value>
      <webElementGuid>c0aa21f7-1619-45fc-b195-811b7574c458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand Tools'])[1]/preceding::div[3]</value>
      <webElementGuid>4c1a470c-49c2-44ab-80a0-8b8bf95c026a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support Items'])[1]/preceding::div[6]</value>
      <webElementGuid>32c2484b-ee01-4598-8324-b8daf39d8e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Men']/parent::*</value>
      <webElementGuid>70b6fd5e-016b-4663-9b65-29b1ee1d39c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a/div</value>
      <webElementGuid>ce2f4a8a-022d-4577-9e4b-65e786c2277f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
