<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nutrition</name>
   <tag></tag>
   <elementGuidId>84e1e349-7ca0-4ed7-86d5-186e38488b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainCategoryItem4']/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainCategoryItem4 > a.styles_mainCategoryLink___k5XX.false > div.styles_mainCategoryTitle__iIvl7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nutrition&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>af4ce8b7-53bb-428a-8ab7-b7cd6a74dfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_mainCategoryTitle__iIvl7</value>
      <webElementGuid>600991d9-6f06-4763-ae7e-e63ada8c9026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nutrition</value>
      <webElementGuid>5fed5162-673c-4665-9f62-7604a3ba661b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainCategoryItem4&quot;)/a[@class=&quot;styles_mainCategoryLink___k5XX false&quot;]/div[@class=&quot;styles_mainCategoryTitle__iIvl7&quot;]</value>
      <webElementGuid>01839163-feaf-401c-a1dd-387c0b333244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainCategoryItem4']/a/div</value>
      <webElementGuid>6eb54780-6b9a-4702-9358-7bb416b80ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark Spots'])[1]/following::div[3]</value>
      <webElementGuid>2d409732-536b-4b6c-b662-e248c576a02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sensitive Skin'])[1]/following::div[6]</value>
      <webElementGuid>d5cacd05-273f-4357-b8ba-1f5b07558c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight Management'])[1]/preceding::div[3]</value>
      <webElementGuid>47a50936-8234-4b55-8e73-3b377b20e6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shakes'])[1]/preceding::div[5]</value>
      <webElementGuid>c2f421c4-1ae0-4b51-8228-7d5a1bcf643c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nutrition']/parent::*</value>
      <webElementGuid>acd022c9-0b4d-4ee9-a6c9-ef255fe6b24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div</value>
      <webElementGuid>fa20f9bd-d0c8-415d-8e16-3c24ebdcce64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
