<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search_lazyImage</name>
   <tag></tag>
   <elementGuidId>07411379-0ab7-4d31-a5b9-2173e401c316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.toggle.loginPanelMainDiv > img.lazyImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainMenuWrapper']/div[2]/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User Menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3d95aa15-538e-4036-ab37-2d5aef7af163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/statics/Content/images/header-icons/user.png</value>
      <webElementGuid>79f8815c-31fd-4b29-8850-02e875466a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/statics/Content/images/header-icons/user.png</value>
      <webElementGuid>e07d1a79-91ed-4048-9601-20d4f792e69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Menu</value>
      <webElementGuid>f67761cf-ad9a-403a-8a06-2c500e4f9a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyImage</value>
      <webElementGuid>ddadbd04-778a-4396-8d9f-b2584f0c7df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>a5ea02d2-0dae-4dce-b320-5a6121510214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3de6d56e-d263-4d29-a981-74cca88f5f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenuWrapper&quot;)/div[2]/div[2]/div[@class=&quot;login-panel&quot;]/div[@class=&quot;toggle loginPanelMainDiv&quot;]/img[@class=&quot;lazyImage&quot;]</value>
      <webElementGuid>11b0ef53-42dd-49d6-80fe-6be05bfc3e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainMenuWrapper']/div[2]/div[2]/div/div/img</value>
      <webElementGuid>1b27458e-c887-45f5-ab29-4fe08cbc4f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Menu']</value>
      <webElementGuid>ee0c4f0a-ff39-47ec-9875-150b0f1f0a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>2595dbd6-8a66-4a53-ab57-725943db0014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/statics/Content/images/header-icons/user.png' and @alt = 'User Menu']</value>
      <webElementGuid>cbbd73ef-8d9e-4503-ad16-b9d447baa579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
