<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>a2610b0a-32a4-4ed7-b3c2-2165a61927c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-button-1545222288830 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-button-1545222288830']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#close-button-1545222288830 >> internal:text=&quot;×&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3860e0f-45e9-47a1-9f47-5bb1eefa3f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>cb9e6780-f80c-4f6b-a4c2-b970ebfca23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-button-1545222288830&quot;)/span[1]</value>
      <webElementGuid>a2557aaa-4cfa-462f-83a4-a5dbc3168d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='close-button-1545222288830']/span</value>
      <webElementGuid>8ba0c152-1c61-4f4e-b3ae-1b12114eca9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add To Cart'])[10]/following::span[1]</value>
      <webElementGuid>fa7bf43a-81ab-42dc-b768-8bebdafc144a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PC Price'])[50]/following::span[1]</value>
      <webElementGuid>14a0498e-992f-4610-be37-00d1f4f12b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[5]/div/span</value>
      <webElementGuid>ff995943-f9fe-4952-a435-6169a6475a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>c6a028ed-0a4c-483e-9055-46e94c628e31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
