<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_CatalogOrdersWishlistBecome a FARMAS_887895</name>
   <tag></tag>
   <elementGuidId>9584f136-080d-402c-910a-15cfc85a0389</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CatalogOrdersWishlistBecome a FARMASI InfluencerCatalogNew ArrivalsFavorite Sets&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>2417618d-db89-44ca-bab6-60344c0c466a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>ec887292-42e0-462c-9f0e-c40763169a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_header__fpulf mb-0</value>
      <webElementGuid>53ee22cd-c29c-4d40-b77c-d2b04b0edf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CatalogOrdersWishlistBecome a FARMASI InfluencerCatalogNew ArrivalsFavorite SetsMakeupEyesMascaraEyeliner/DiplinerEyeshadow PalettesEyeshadowEye PrimerEyebrowEye Make Up CleanserLipsLiquid LipstickLipstickLip GlossLip LinerLip SetsLip Balm &amp; TreatmentLatina CollectionFace &amp; BodyFoundationBB &amp; CC CreamsPrimerConcealerPowderBlushBronzerHighlighter &amp; ContourSetting Spray &amp; PowderMakeup RemoversAccessoriesBrushes &amp; SpongesSkin CareShop by SeriesAbsoluteAge ReversistAquaLumi RadianceCalendulaTea TreeResurfaceShop by CategoryMoisturizers &amp; Face CreamsCleansersSerums &amp; TreatmentsFace MasksTonersEye CareShop by ConcernWrinkles &amp; Fine LinesOilinessDrynessSensitive SkinEnlarged PoresDark SpotsNutritionWeight ManagementShakesVitaminsCoffees&amp;TeasCollagen and BeautyNutriplus SolutionsGeneral HealthBeautySelf-CareSoapsHand Care &amp; Foot CareOral CareFragrancesBath &amp; Body CareSun CareBody TreatmentEssential OilsOilsDiffuserHair CareShampooConditioner &amp; MaskOils &amp; Serums &amp; SpraysSeriesHome CareLaundryDishwashingMultipurpose CleanerAccessoriesMenBrand ToolsSupport ItemsFarmasi Gear</value>
      <webElementGuid>538f0fe9-43c4-4f02-956c-18cb8b6b33b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)</value>
      <webElementGuid>912c73e0-d6cc-4573-ab78-6fe94e4e32ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//header[@id='header']</value>
      <webElementGuid>c66fb682-0df6-4bf9-9cd0-f1815b8c9696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header</value>
      <webElementGuid>8225a640-c7d0-4389-a2b5-6ced3bedfee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>27669b0b-435f-4171-b6bf-47c742800378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[@id = 'header' and (text() = 'CatalogOrdersWishlistBecome a FARMASI InfluencerCatalogNew ArrivalsFavorite SetsMakeupEyesMascaraEyeliner/DiplinerEyeshadow PalettesEyeshadowEye PrimerEyebrowEye Make Up CleanserLipsLiquid LipstickLipstickLip GlossLip LinerLip SetsLip Balm &amp; TreatmentLatina CollectionFace &amp; BodyFoundationBB &amp; CC CreamsPrimerConcealerPowderBlushBronzerHighlighter &amp; ContourSetting Spray &amp; PowderMakeup RemoversAccessoriesBrushes &amp; SpongesSkin CareShop by SeriesAbsoluteAge ReversistAquaLumi RadianceCalendulaTea TreeResurfaceShop by CategoryMoisturizers &amp; Face CreamsCleansersSerums &amp; TreatmentsFace MasksTonersEye CareShop by ConcernWrinkles &amp; Fine LinesOilinessDrynessSensitive SkinEnlarged PoresDark SpotsNutritionWeight ManagementShakesVitaminsCoffees&amp;TeasCollagen and BeautyNutriplus SolutionsGeneral HealthBeautySelf-CareSoapsHand Care &amp; Foot CareOral CareFragrancesBath &amp; Body CareSun CareBody TreatmentEssential OilsOilsDiffuserHair CareShampooConditioner &amp; MaskOils &amp; Serums &amp; SpraysSeriesHome CareLaundryDishwashingMultipurpose CleanerAccessoriesMenBrand ToolsSupport ItemsFarmasi Gear' or . = 'CatalogOrdersWishlistBecome a FARMASI InfluencerCatalogNew ArrivalsFavorite SetsMakeupEyesMascaraEyeliner/DiplinerEyeshadow PalettesEyeshadowEye PrimerEyebrowEye Make Up CleanserLipsLiquid LipstickLipstickLip GlossLip LinerLip SetsLip Balm &amp; TreatmentLatina CollectionFace &amp; BodyFoundationBB &amp; CC CreamsPrimerConcealerPowderBlushBronzerHighlighter &amp; ContourSetting Spray &amp; PowderMakeup RemoversAccessoriesBrushes &amp; SpongesSkin CareShop by SeriesAbsoluteAge ReversistAquaLumi RadianceCalendulaTea TreeResurfaceShop by CategoryMoisturizers &amp; Face CreamsCleansersSerums &amp; TreatmentsFace MasksTonersEye CareShop by ConcernWrinkles &amp; Fine LinesOilinessDrynessSensitive SkinEnlarged PoresDark SpotsNutritionWeight ManagementShakesVitaminsCoffees&amp;TeasCollagen and BeautyNutriplus SolutionsGeneral HealthBeautySelf-CareSoapsHand Care &amp; Foot CareOral CareFragrancesBath &amp; Body CareSun CareBody TreatmentEssential OilsOilsDiffuserHair CareShampooConditioner &amp; MaskOils &amp; Serums &amp; SpraysSeriesHome CareLaundryDishwashingMultipurpose CleanerAccessoriesMenBrand ToolsSupport ItemsFarmasi Gear')]</value>
      <webElementGuid>9cd9f93f-f393-48be-9bf8-870a0af8e9c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
