<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EN_styles_image__qb0tG</name>
   <tag></tag>
   <elementGuidId>24ac4cf1-5b94-4979-8da2-88bac8101f82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.styles_image__qb0tG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;User Profile Picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>71dfa4b5-1a82-49c0-8faf-0a96c59e4437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://farmasi-customer-v2.s3.eu-west-1.amazonaws.com/Profile/b739257e-616b-4132-aa25-dea995aef58c.JPG</value>
      <webElementGuid>0009503d-69d8-4db0-8ce6-f914655b0195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>User Profile Picture</value>
      <webElementGuid>ed28d362-f3fd-4c3d-8cbb-0fb0fb056f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>88256f99-ce29-4619-be3d-eb225a3b8495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_image__qb0tG</value>
      <webElementGuid>dad31c61-f1df-4e77-8d96-7bb5e22c9f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;container styles_headerUpper__diGEV&quot;]/div[@class=&quot;styles_headerUpperRight__ZW4WC&quot;]/div[@class=&quot;styles_container__A_H4H&quot;]/div[1]/div[1]/div[@class=&quot;styles_container__BfiT7&quot;]/img[@class=&quot;styles_image__qb0tG&quot;]</value>
      <webElementGuid>c4d8b60e-f455-4ef7-80ed-69d715937115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div[2]/div[2]/div/div/div/img</value>
      <webElementGuid>5ec35fb2-e70a-4a49-bc29-8c266acfbf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='User Profile Picture']</value>
      <webElementGuid>3c1db488-2b68-43d6-9505-11d022ee6e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>0190ca34-dc72-4140-b770-7219944791f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://farmasi-customer-v2.s3.eu-west-1.amazonaws.com/Profile/b739257e-616b-4132-aa25-dea995aef58c.JPG' and @alt = 'User Profile Picture']</value>
      <webElementGuid>24bba012-f73d-40cd-9ce7-0d0d81796bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
