<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Products</name>
   <tag></tag>
   <elementGuidId>cbe45502-a30e-40d4-8e63-e1e21bde624d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/form/div[12]/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_title__OqQdn.styles_defaults__ttgfN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Products&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ac223a7-18f0-4a67-ab51-cbe93c88371f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_title__OqQdn styles_defaults__ttgfN undefined</value>
      <webElementGuid>b395684c-8a4c-4302-82cf-e2ff94b18b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Products</value>
      <webElementGuid>21dbe1a1-4e16-4256-bc8e-cb40aeeda880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;checkout_container__n0Pdj container&quot;]/form[@class=&quot;checkout_content__9prD6&quot;]/div[@class=&quot;styles_container__EnWsw&quot;]/div[@class=&quot;styles_container__BK9qG styles_accordionContainer__eGfFF&quot;]/div[@class=&quot;styles_accordionItem__n7xC5&quot;]/button[@class=&quot;styles_accordionItemButton__xMyMX styles_accordionItem__BNxvp&quot;]/div[@class=&quot;styles_title__OqQdn styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>810a1d4a-dec4-48cb-bbdb-457a9bc779d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/form/div[12]/div/div/button/div</value>
      <webElementGuid>2af20bff-fc49-4ea0-9baf-a13fd372d179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distance selling contract and terms of use Farmasi.'])[1]/following::div[4]</value>
      <webElementGuid>0a2dc6ca-585f-49c9-87a9-6ed7c6febb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose another way to pay'])[1]/following::div[11]</value>
      <webElementGuid>558d0224-fd82-439a-9649-e4dc82e45cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creamy Lipstick - 14 Scarlet'])[1]/preceding::div[4]</value>
      <webElementGuid>d89562dc-8c38-43b8-999b-604b3520600f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$10.75'])[1]/preceding::div[9]</value>
      <webElementGuid>3af59eda-7bba-462b-b926-43b9adb9f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Products']/parent::*</value>
      <webElementGuid>7e41e6c3-77e1-4d57-b9da-f4bbe4e07656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>90267423-31a4-475d-9d06-d2006d6547c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Products' or . = 'Products')]</value>
      <webElementGuid>82f66e78-e91e-4d2d-94cb-bed78b4695a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BB Glaze Lipstick Pink Beige 05'])[1]/preceding::div[4]</value>
      <webElementGuid>a9d000a7-4f38-4bf8-88cf-6b57a282199c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pink Beige 05 -'])[1]/preceding::div[7]</value>
      <webElementGuid>704a5841-f78f-4679-94fb-2d2f9d85360c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
