<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_deneme1</name>
   <tag></tag>
   <elementGuidId>933e90b0-64e8-4f9d-a505-a4b4810c0402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.styles_welcomeMessage__YnPK1.styles_defaults__ttgfN.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;deneme1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c2546cd-0834-4000-9454-b81d70760aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_welcomeMessage__YnPK1 styles_defaults__ttgfN undefined</value>
      <webElementGuid>9e0587f0-c2d3-4882-91d5-03a8a8424811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>deneme1</value>
      <webElementGuid>4743fd4a-fd9f-493d-9b9a-0659fac5ce56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container styles_container__K6XM3&quot;]/div[@class=&quot;styles_content___n5NY&quot;]/div[@class=&quot;profile_profile__TdQuK&quot;]/div[@class=&quot;styles_container__vjz2I&quot;]/div[@class=&quot;styles_content__F0h57&quot;]/div[3]/div[@class=&quot;styles_welcomeMessageContainer__CbdZc&quot;]/span[@class=&quot;styles_welcomeMessage__YnPK1 styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>1b3517c9-0773-4a6d-90dc-d5d733c2e1e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div[2]/div[3]/div[2]/div[3]/div/span</value>
      <webElementGuid>6a907c0f-57b1-4ee3-b304-4c760819bf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Message on Personal Page'])[1]/following::span[1]</value>
      <webElementGuid>9c69a96e-4f91-4589-8586-7527a9353ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/farmasi'])[7]/following::span[2]</value>
      <webElementGuid>c45d68a2-b018-4557-943f-241c9aad1037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Personal Website'])[1]/preceding::span[1]</value>
      <webElementGuid>639da484-8efe-4af3-b3ea-043723889b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Website'])[2]/preceding::span[1]</value>
      <webElementGuid>e7585de1-3811-4823-970b-c3d8090e2e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='deneme1']/parent::*</value>
      <webElementGuid>3eab7fc2-8363-4347-8393-ee92b08d7691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>3820c69c-8f8d-43bc-aa55-8531b343ff99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
