<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>8f468694-841d-4d31-a9bd-c5422dc8db19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@data-testid = 'inputButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.styles_inputBtn__o65gF.false</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;inputButton&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e6e950b-4531-43d1-a565-bcb12a79c765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_inputBtn__o65gF false  </value>
      <webElementGuid>882f78cf-8a71-409e-bd0e-897be76ab483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0adcb47-76b5-4ee6-95ce-2b35194446b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>inputButton</value>
      <webElementGuid>a52e426d-1f49-42de-87ac-a098636ea968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>d956ea3a-664f-494d-96f0-23c686446207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;checkout_container__n0Pdj container&quot;]/form[@class=&quot;checkout_content__9prD6&quot;]/div[@class=&quot;styles_wallet__Hklg0&quot;]/div[@class=&quot;styles_walletInput___FjCU&quot;]/div[@class=&quot;styles_walletInputContainer__R7FXx&quot;]/div[1]/div[@class=&quot;styles_inputGroup__ro902 false  false styles_inputGroupReverse__VOiCp&quot;]/div[@class=&quot;styles_iconGroup__d8wY1 undefined&quot;]/button[@class=&quot;styles_inputBtn__o65gF false&quot;]</value>
      <webElementGuid>7f9c3927-1069-45f3-8204-27ae07f9491b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@data-testid = 'inputButton']</value>
      <webElementGuid>d41317be-9073-43a6-98d4-178e4e7fe2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/form/div[8]/div[2]/div[2]/div/div/div[2]/button</value>
      <webElementGuid>b585b5e3-5ded-4d02-99d5-b95940c19b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>8f453050-4ce7-4bb3-a4a2-229e0e369ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::button[1]</value>
      <webElementGuid>9aa86f55-a1c3-4f84-a1b0-21003ae2b62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1252.79'])[1]/following::button[1]</value>
      <webElementGuid>93ac01e1-d884-43e7-826e-54ae43d9e80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal'])[1]/preceding::button[1]</value>
      <webElementGuid>736a68c7-f340-44dc-9367-217a0d78fb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3d173793-2fcd-4694-b18b-6d5a0a31ba39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
