<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1274.45_walletBalance</name>
   <tag></tag>
   <elementGuidId>eda2923f-eae6-470e-9e1f-1199b3180dd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/form/div[8]/div[2]/div[2]/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;walletBalance&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Amount&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8acee8db-9ef1-4489-be60-c48543b40afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>walletBalance</value>
      <webElementGuid>7177b2c8-72ec-4c7b-a1c0-4c53c9b37b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>ee4e637f-2267-4f2e-b273-b036e7596a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>321cfff6-6a57-4732-9656-9bbd6c976fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28c00b1d-9a05-421c-aaa1-5804aa4a297b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__ZqX_f false   form-control</value>
      <webElementGuid>ca5517a8-8e48-4db3-b5b0-c3ad7bf36a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>19.25</value>
      <webElementGuid>e3b2ee6f-4a79-4beb-9c92-9b7e7fcb28ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;checkout_container__n0Pdj container&quot;]/form[@class=&quot;checkout_content__9prD6&quot;]/div[@class=&quot;styles_wallet__Hklg0&quot;]/div[@class=&quot;styles_walletInput___FjCU&quot;]/div[@class=&quot;styles_walletInputContainer__R7FXx&quot;]/div[1]/div[@class=&quot;styles_inputGroup__ro902 false  false styles_inputGroupReverse__VOiCp&quot;]/div[@class=&quot;styles_inputContainer__kvPuU undefined&quot;]/div[@class=&quot;styles_floatingLabel__99vA6 form-floating&quot;]/input[@class=&quot;styles_input__ZqX_f false   form-control&quot;]</value>
      <webElementGuid>021eb671-7273-4659-9b7b-36259d993802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/form/div[8]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>33a1e6a1-7141-4431-bbd5-efced037dce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='walletBalance']</value>
      <webElementGuid>ea59b17e-d5d2-4022-9f39-eabaffad8427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>d90bf806-1948-4447-b95e-70270491ccfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
