<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EN_styles_background__J62ut</name>
   <tag></tag>
   <elementGuidId>88942001-6772-4c5f-9c50-6c1f5a3add82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_background__J62ut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.styles_background__J62ut</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3cc02e3-a487-465b-9156-c76861c04ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_background__J62ut</value>
      <webElementGuid>e6682366-21e4-4012-bdcb-4086f1d323fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;styles_container__8yfol&quot;]/div[@class=&quot;styles_background__J62ut&quot;]</value>
      <webElementGuid>0983ea47-bcd4-4e5b-8816-9f7b8bd8aa09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div</value>
      <webElementGuid>7146eb0d-4c9d-476e-b78c-a066cce49ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>a05abc7b-59e9-476b-af4a-99fae2e799da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
