<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>5b0538b2-d4ee-485c-81de-3f1af5d384c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Apply$/ >> circle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>564005c1-b869-4970-aef6-5bc26e22cc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>189874a8-2db6-4ff0-a0d1-276a304d338a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>272d9b9a-3075-4614-8548-93c83227ab0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ff5091c4-695f-4b4c-9d7e-f49b9a09c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#D11A25</value>
      <webElementGuid>ba77058b-4030-49be-a804-4b9fea8bf50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;checkout_container__n0Pdj container&quot;]/form[@class=&quot;checkout_content__9prD6&quot;]/div[@class=&quot;styles_wallet__Hklg0&quot;]/div[@class=&quot;styles_walletInput___FjCU&quot;]/div[@class=&quot;styles_walletInputContainer__R7FXx&quot;]/div[1]/div[@class=&quot;styles_inputGroup__ro902 false  false styles_inputGroupReverse__VOiCp styles_inputGroupError__2Obm3&quot;]/div[@class=&quot;styles_iconGroup__d8wY1 undefined&quot;]/svg[1]/circle[1]</value>
      <webElementGuid>e1cbe503-bd01-40ff-83f6-bffd819e738d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
