<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Distance selling contract and terms o_cd7b5c</name>
   <tag></tag>
   <elementGuidId>8c5cf0fc-002a-412d-8b27-1008c1a2f157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='agreements'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styles_agreement__gM1sz.m-0 > div.styles_container__K8wFn > div > div.styles_containerCheckBox__1uCkp > input[name=&quot;agreements&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Distance selling contract and terms of use Farmasi.InformationYou must confirm t&quot;i >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0053968-5bd7-4195-b7cd-972dadadd83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__bxkI7</value>
      <webElementGuid>0ceb124f-30b2-4f15-8bb7-6e34dce682ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>676838ce-8453-4107-822b-7036bdc2da7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agreements</value>
      <webElementGuid>584931b6-feec-4071-a5b1-00343b9cafa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>55ab8a99-c052-4278-ac67-07345a0427a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>676526d9-da9e-4a85-847a-15016bbd2f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;styles_window__xaCFD styles_roundedmedium__nXKE3 undefined&quot;]/div[@class=&quot;styles_content__Yf1T7 styles_modalPadding__0mbnS styles_maxContentHeight__wZWPT undefined&quot;]/div[@class=&quot;styles_agreement__gM1sz m-0&quot;]/div[@class=&quot;styles_container__K8wFn&quot;]/div[1]/div[@class=&quot;styles_containerCheckBox__1uCkp&quot;]/input[@class=&quot;styles_input__bxkI7&quot;]</value>
      <webElementGuid>f76eef99-a3e6-45bb-92ff-bc06b12274c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='agreements'])[2]</value>
      <webElementGuid>daba2a2b-f2c7-4f3b-99f2-415c653ab526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>6aac864b-9ae5-448c-877b-f1313d53b3f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
