<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_deneme1</name>
   <tag></tag>
   <elementGuidId>1ecdc64f-ec4e-4b39-bda5-e84428f2c8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/main/div[1]/div/div[2]/form/div[5]/div/div/div[1]/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;welcomeMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;deneme1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>636429ad-2184-4024-9ab7-8bea868cd43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>welcomeMessage</value>
      <webElementGuid>1a165b8e-86a3-46fb-806f-b671637984ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a3d7729-de26-4cce-a1ef-43cd95244561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_input__tFS_Y styles_inputFocused__f2_zm form-control</value>
      <webElementGuid>8502cc28-6ce8-4c4e-a40c-d624a891f10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>deneme1</value>
      <webElementGuid>51e1ef8f-fbbb-49d1-873a-161eedd2a669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container updatePersonalWebsite_container__8sEZN&quot;]/div[@class=&quot;updatePersonalWebsite_containerContent__cw7M7&quot;]/div[@class=&quot;updatePersonalWebsite_content__wCUic&quot;]/form[@class=&quot;updatePersonalWebsite_form__P0awv&quot;]/div[@class=&quot;updatePersonalWebsite_section__JYKdK&quot;]/div[1]/div[@class=&quot;styles_inputGroup__DU0_L styles_inputGroupFocused__zrfgr  false&quot;]/div[@class=&quot;styles_inputContainer__cc_Aw&quot;]/div[@class=&quot;styles_floatingLabel__BTt5O form-floating&quot;]/textarea[@class=&quot;styles_input__tFS_Y styles_inputFocused__f2_zm form-control&quot;]</value>
      <webElementGuid>1afaf1f1-ad8e-4d29-9e47-1e4fc5b79dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div[2]/form/div[5]/div/div/div/div/textarea</value>
      <webElementGuid>bea992a0-af89-48c7-be26-f66f91f25b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='welcomeMessage']</value>
      <webElementGuid>f3edcb62-4e20-4ae9-9958-a2568663bb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Message on Personal Page'])[1]/following::textarea[1]</value>
      <webElementGuid>94a95ef0-087a-4b03-bccb-74d4ffc5f922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiktok URL'])[1]/following::textarea[1]</value>
      <webElementGuid>9cc02ed0-4127-410c-a0fb-16ab09635895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save My Information'])[1]/preceding::textarea[1]</value>
      <webElementGuid>33c319b3-dfeb-4905-ad98-fd42637cc660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow us on Social Media!'])[1]/preceding::textarea[1]</value>
      <webElementGuid>be45fa74-35e7-43cb-a971-0e3e273a7462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='deneme1']/parent::*</value>
      <webElementGuid>a9e83f07-06b7-4470-baa5-cc2e3d42df11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>da6ea670-6465-472f-a9ce-0de30fe63eda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
