<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nutrition</name>
   <tag></tag>
   <elementGuidId>0b931488-d300-4109-a4f6-1a26c44c75f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainCategoryItem4 > a.styles_mainCategoryLink___k5XX.false > div.styles_mainCategoryTitle__iIvl7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainCategoryItem4']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nutrition&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4391bfe-7598-408f-99c5-517b31d972a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_mainCategoryTitle__iIvl7</value>
      <webElementGuid>ba13b507-65f7-4027-863c-c1992d81f11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nutrition</value>
      <webElementGuid>d67c6c7a-ecbf-4430-8058-766d3477a55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainCategoryItem4&quot;)/a[@class=&quot;styles_mainCategoryLink___k5XX false&quot;]/div[@class=&quot;styles_mainCategoryTitle__iIvl7&quot;]</value>
      <webElementGuid>02a563c9-e8db-4ad0-8f81-f2649b3a8e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainCategoryItem4']/a/div</value>
      <webElementGuid>88c95d70-adae-40be-9be2-23c066753e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark Spots'])[1]/following::div[3]</value>
      <webElementGuid>b5e8a608-9fed-42ed-ae8e-4fc1436d9d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enlarged Pores'])[1]/following::div[6]</value>
      <webElementGuid>d8c5d91c-69ea-4c37-add5-f408cb49414e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight Management'])[1]/preceding::div[3]</value>
      <webElementGuid>5e3cc0eb-5794-4468-bb08-03eb6836d743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shakes'])[1]/preceding::div[5]</value>
      <webElementGuid>cda41561-1cbd-4b13-a6a2-84b7c3be91ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nutrition']/parent::*</value>
      <webElementGuid>2c7130be-0c98-41eb-8fd6-7bebf41d7802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div</value>
      <webElementGuid>e5f0cd56-26e3-4a26-95b4-6bad33b01087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nutrition' or . = 'Nutrition')]</value>
      <webElementGuid>a2e3d7fd-2115-4476-a99b-23e256bc7e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
