<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_otomasyon2</name>
   <tag></tag>
   <elementGuidId>58514eac-9d1b-47d4-88bc-84e9bbb68b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.wishlistDetail_heading__Rkcy0.styles_defaults__ttgfN.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@data-testid = 'listName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;listName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b03dea2d-33b6-4a92-9cdd-59ff8dbb378a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wishlistDetail_heading__Rkcy0 styles_defaults__ttgfN undefined</value>
      <webElementGuid>8a081320-2564-410a-9745-839fe859b12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>listName</value>
      <webElementGuid>311f9150-cfd2-4263-9ed4-2eee3b908fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>otomasyon2</value>
      <webElementGuid>b9c053c5-a991-437b-b61c-d4f155eba759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container wishlistDetail_container__7Fd22&quot;]/section[@class=&quot;wishlistDetail_toolbar__JgwZo&quot;]/h1[@class=&quot;wishlistDetail_heading__Rkcy0 styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>d4ed0342-7c41-4d58-91c2-9aee572629ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@data-testid = 'listName']</value>
      <webElementGuid>4ddd300e-facc-4be0-8832-0e176206980e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/section/h1</value>
      <webElementGuid>2de6d1d4-d239-4a3c-a284-2e51a7062ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Gear'])[1]/following::h1[1]</value>
      <webElementGuid>a60df955-4dfd-40e4-8395-5790e54a67a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support Items'])[1]/following::h1[1]</value>
      <webElementGuid>b9fa8d7e-3f89-4f4f-9711-e9be6337ddb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add All to Cart'])[1]/preceding::h1[1]</value>
      <webElementGuid>00153c89-e8ad-4c69-9181-528cdb358a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='otomasyon2']/parent::*</value>
      <webElementGuid>7af07489-f411-41b5-a854-e3b77f167941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>ee02f232-7811-4767-8bff-24598933c492</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
