<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_otomasyon</name>
   <tag></tag>
   <elementGuidId>f7064f8c-14cd-47f1-9ea4-861b6156ef3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.wishlistDetail_heading__Rkcy0.styles_defaults__ttgfN.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@data-testid = 'listName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;listName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a60fed62-21ea-4f3f-8848-c1c56a63b614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wishlistDetail_heading__Rkcy0 styles_defaults__ttgfN undefined</value>
      <webElementGuid>6c6fff6f-4cf2-4249-8685-98a61921fd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>listName</value>
      <webElementGuid>e06702c2-65cb-4c7e-af1e-579b0287948c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>otomasyon</value>
      <webElementGuid>79bfc45f-2476-43c2-8b17-41e3d7658255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;styles_layout__M1JA_&quot;]/main[1]/div[@class=&quot;container wishlistDetail_container__7Fd22&quot;]/section[@class=&quot;wishlistDetail_toolbar__JgwZo&quot;]/h1[@class=&quot;wishlistDetail_heading__Rkcy0 styles_defaults__ttgfN undefined&quot;]</value>
      <webElementGuid>e4deae1c-3c8b-4ff8-89fa-7fab95ff172b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@data-testid = 'listName']</value>
      <webElementGuid>1e1c8683-d5de-4b3f-ba08-3a73b3499e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/section/h1</value>
      <webElementGuid>b9af6f55-ef7b-41d4-aced-9e3dd3cd6e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmasi Gear'])[1]/following::h1[1]</value>
      <webElementGuid>5c70029f-796c-45ca-8f40-437e57dec5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support Items'])[1]/following::h1[1]</value>
      <webElementGuid>187033d0-0164-4798-b4eb-b1dd73e04797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add All to Cart'])[1]/preceding::h1[1]</value>
      <webElementGuid>8df4bb45-6b70-4485-9100-5f6e05c6905f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='otomasyon']/parent::*</value>
      <webElementGuid>e077e6b3-9d1a-4be1-9fe4-cc0d09d42b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b91a7be4-2086-4971-a42c-866b5f2ea129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
