<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Makeup</name>
   <tag></tag>
   <elementGuidId>b7c41730-e8f3-4c5b-883e-dc88cecd697b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainCategoryItem2']/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainCategoryItem2 > a.styles_mainCategoryLink___k5XX.false > div.styles_mainCategoryTitle__iIvl7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Makeup&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>251ed4b5-f188-4bb9-8042-46597c383ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_mainCategoryTitle__iIvl7</value>
      <webElementGuid>66fc5f28-2708-48f4-87bf-5717b57de7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Makeup</value>
      <webElementGuid>1629eefc-cd22-4476-93bf-466e7557c116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainCategoryItem2&quot;)/a[@class=&quot;styles_mainCategoryLink___k5XX false&quot;]/div[@class=&quot;styles_mainCategoryTitle__iIvl7&quot;]</value>
      <webElementGuid>8ae0d596-a2aa-4f39-b695-7e3a85f70e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainCategoryItem2']/a/div</value>
      <webElementGuid>90aef557-a5f0-4ed2-a9f8-01e72b6bd2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorite Sets'])[1]/following::div[4]</value>
      <webElementGuid>d50ce324-606d-4cac-b54c-1b0d04d657a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Arrivals'])[1]/following::div[8]</value>
      <webElementGuid>009701fa-0f40-4da5-88cd-b9f55a15beb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eyes'])[1]/preceding::div[3]</value>
      <webElementGuid>a2c091cf-9ba6-4f3e-a2e3-461717a58570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mascara'])[1]/preceding::div[4]</value>
      <webElementGuid>8a5a7e36-eaf4-48bd-b455-07e603aae342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Makeup']/parent::*</value>
      <webElementGuid>0183d997-6905-4feb-b7f3-91d7bf2206d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div</value>
      <webElementGuid>761f7066-d325-4a6f-9ec5-dfb73671ce9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
